// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjXpsUvfhlT6_HecK549UMmXKZA0YeJTw',
    appId: '1:432071771632:web:1ed0180b3971812fd78935',
    messagingSenderId: '432071771632',
    projectId: 'tastyrecipes-b133a',
    authDomain: 'tastyrecipes-b133a.firebaseapp.com',
    storageBucket: 'tastyrecipes-b133a.appspot.com',
    measurementId: 'G-65C4M721HR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZ7Omx3AJXpV3YrawUFgrlyBR3uWwh6IA',
    appId: '1:432071771632:android:88904dc12976a702d78935',
    messagingSenderId: '432071771632',
    projectId: 'tastyrecipes-b133a',
    storageBucket: 'tastyrecipes-b133a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbacAfT4JFqjuqiJ9RQeKg4M0AgU8-j_Y',
    appId: '1:432071771632:ios:7335fe6c4644a78cd78935',
    messagingSenderId: '432071771632',
    projectId: 'tastyrecipes-b133a',
    storageBucket: 'tastyrecipes-b133a.appspot.com',
    androidClientId: '432071771632-vnnui9e94k2au6lhtgsuod0175ajista.apps.googleusercontent.com',
    iosClientId: '432071771632-6pjgjn2tnjev7g5p5tm0o0nju7k7isnh.apps.googleusercontent.com',
    iosBundleId: 'fr.philippot.yannis.tastyRecipes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDbacAfT4JFqjuqiJ9RQeKg4M0AgU8-j_Y',
    appId: '1:432071771632:ios:7335fe6c4644a78cd78935',
    messagingSenderId: '432071771632',
    projectId: 'tastyrecipes-b133a',
    storageBucket: 'tastyrecipes-b133a.appspot.com',
    androidClientId: '432071771632-vnnui9e94k2au6lhtgsuod0175ajista.apps.googleusercontent.com',
    iosClientId: '432071771632-6pjgjn2tnjev7g5p5tm0o0nju7k7isnh.apps.googleusercontent.com',
    iosBundleId: 'fr.philippot.yannis.tastyRecipes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCjXpsUvfhlT6_HecK549UMmXKZA0YeJTw',
    appId: '1:432071771632:web:5fdbc29a5f5912e4d78935',
    messagingSenderId: '432071771632',
    projectId: 'tastyrecipes-b133a',
    authDomain: 'tastyrecipes-b133a.firebaseapp.com',
    storageBucket: 'tastyrecipes-b133a.appspot.com',
    measurementId: 'G-EHFYHFPTTN',
  );

}